### ISSUE TITLE
Allow a text element to be supplied in constructor

### ISSUE THREAD

**Issue by voracious** [voracious/ink-mde#28]
For better progressive enhancement, a text element should be an acceptable "parent" element. It might require some investigation, but a naive approach, for now, would be to replace that element with a normal container (such as a div).

**Comment by voraciousdev** [comment]
When a text element is supplied, Ink could also set the element to hidden and keep the value in sync with the actual editor.

**Comment by voracious** [comment]
Thanks, @asecondwill! That's essentially the idea, although you'd need to iterate the elements and initialize each of them right now. Something like this would work.

```ts
Array.from(document.getElementsByClassName('editor')).forEach((editor) => {
  ink(editor)
})
```
