### ISSUE TITLE
Allow opt-out/opt-in for language specific syntax library

### ISSUE THREAD

**Issue by meismann-as** [voracious/ink-mde#49]
We use Ink-MDE in a Vue.js app as a Markdown editor for its wonderful wysiwyg-syntax-highlighting. When building the project (`yarn build`), I noticed more than forty dependencies, most of which are specific to a certain programming language. At the end, yarn printed a warning: 

> (!) Some chunks are larger than 500 KiB after minification. Consider:
> - Using dynamic import() to code-split the application
> - Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/guide/en/#outputmanualchunks
> - Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.

I would like to be able to restrict the language-dependencies bundled into my app to the one I need, Markdown in our case. As this relates to bundle size, I imagine other users, too, to appreciate the possibility to reduce the supported languages to only the subset needed. Could this be a future feature—or is there already a way to do this?

**Comment by voracious** [comment]
Hey there, @meismann-as! I'm really glad to hear you are enjoying it. 😄 

It sounds like there might be an issue with your bundler configuration. Most of the modules and dependencies of `ink-mde` are already split into individual smaller chunks that only get included in your project when used. As for the language dependencies, those are included for highlighting various languages inside of Markdown code blocks. If you have a link to your project or another example, I'd be happy to take a look at it to see if there's something I can do.

**Comment by meismann-as** [comment]
Hi, thank you for replying so quickly and offering help! Hm, big chunks seem to be an issue of my `yarn` configuration, that makes sense. I will go and check back there (our client's private repo, so I am sorry not to be able to provide insight). However, we will not support language highlighting in Markdown code blocks; in fact, we expect the user not to write any code there at all apart from Markdown. From your reply I take it that limiting the language highlighting support to a subset of languages to reduce dependencies is not a feature so far, is that right? If so, could it be a future feature?

**Comment by voracious** [comment]
Not a problem at all! I think it makes sense for code blocks to be configurable. As for individual languages, I think I'd need to see what kind of bundler configuration would make that necessary since those are already individual chunks.

**Comment by meismann-as** [comment]
I was wrong in my assumption that the language highlighting deps would get bundled into the index.js and imported by default. Instead, e.g. the Ruby chunk gets loaded only when I try to write Ruby in the editor. Very neat!
The chunk over 500kB, that `yarn build` warned my about, is index.js. This is because after including Ink-MDE in the bundle, index.js grows from previously 252kB to 789kB. I think we will have to make do with that. Thank you for your efforts!

**Comment by voracious** [comment]
> This is because after including Ink-MDE in the bundle, index.js grows from previously 252kB to 789kB.

@meismann-as that definitely makes sense. I am still working to reduce the overall bundle size of the main import, but a big part of that is CodeMirror itself. If you don't want your main entry to be that large, you could either dynamically initialize `ink-mde` (e.g. `const { ink } = await import('ink-mde')`, or you could create a separate chunk manually.
