### ISSUE TITLE
svelte wrapper

### ISSUE THREAD

**Issue by demetrius-mp** [voracious/ink-mde#51]
i dont know if you have any interest on a svelte wrapper for this component, but i have created the following [ink-mde-svelte](https://github.com/demetrius-mp/ink-mde-svelte) package. Also published on [npm](https://www.npmjs.com/package/ink-mde-svelte).

if you want to move it to this repo, or move it to your account, i'd be happy to help.

**Comment by voracious** [comment]
Hey there, @demetrius-mp! Thanks so much for putting this together. 🎉 

I'm always interested in making it easier to use `ink-mde` in more frameworks and configurations, and I'm absolutely open to merging your package into this repo. Would you be open to submitting a PR that adds your project under a folder called `svelte`?

**Comment by demetrius-mp** [comment]
sure!

**Comment by demetrius-mp** [comment]
im having some problems:

I was checking your `/vue` folder, and i noticed you dont use typescript to add type declarations, since vue provides their own way of typing. But svelte only uses typescript to provide type declarations. 

To keep a godd developer experience both for the users of the package, and the people who will maintain the svelte component, the best way of creating the package would be to use [svelte kit packaging](https://kit.svelte.dev/docs/packaging). 

Basically, this will handle separating the types (on a .svelte.d.ts) file, from the component itself, which allows for both TS and JS users to use the component, while the maintainer can work on a single file that glues svelte and typescript code.

However, **i think** there is no way to put the sveltekit project under a `/svelte` folder, and export the component correctly.

One solution i can think of would be to either turn this into a monorepo with would have the `ink-mde` repo, `@ink-mde/vue`, and `@ink-mde/svelte` or any other frameworks you wish to support.

The other solution would be to keep it in a separate repo. If you want to do this way, i could transfer ownership of my repo to you.

**Comment by voracious** [comment]
So, Vue does have its own method of providing prop types, but I am actually using TypeScript to generate the types for the Vue component. As for SvelteKit, you can actually drop the entire project into its own folder and then use a [conditional export](https://github.com/voracious/ink-mde/blob/main/package.json#L51) to help Node resolve the correct path in the top-level package.json.

**Comment by demetrius-mp** [comment]
hmm, i see

just to be sure:
sveltekit packaging will create a `/package` folder in its root (on the same folder as its `/src` folder)

this `/package` folder is on .gitignore

what you are asking me to do is to remove it from the gitignore, so that it can be seen accessible 
on `/svelte/package.json`, and then, export the component

after this, i need to add the conditional export to the `ink-mde` root `package.json`.

is that it? geez im sorry for such long texts, ive never did anything related to packaging before

**Comment by voracious** [comment]
> sveltekit packaging will create a /package folder in its root (on the same folder as its /src folder)

That sounds right. Vite currently creates a `dist` folder that is ignored as well.

> what you are asking me to do is to remove it from the gitignore, so that it can be seen accessible
on `/svelte/package.json`, and then, export the component

This step is actually unnecessary. We don't want to keep the build in version control. Instead, the build step will run as a part of the deploy process. The [current build command](https://github.com/voracious/ink-mde/blob/83a53ad9cd28bd455f927ff4917534204ed867ac/package.json#L81-L83) runs for both the standalone package (`build:root`) and the Vue package (`build:vue`). This will be another command called `build:svelte`. The top-level `package.json` will then have extra exports that point to the `/svelte/package` folder.

Don't worry if it's confusing. This type of packaging is definitely a bit more complicated than most you'd find out there. If you are still open to submitting a PR, I'm happy to either commit changes related to packaging or leave a review with more detailed instructions. Either way, I really appreciate your efforts on this!

**Comment by demetrius-mp** [comment]
oooh now that you mentioned about the extra `build:*` commands, i can see how it would work.

im going to open a PR adding the `svelte/` folder with the sveltekit project inside, and you can do the packaging related stuff

**Comment by voracious** [comment]
This is now available in [`v0.19.0`](https://github.com/voracious/ink-mde/releases/tag/v0.19.0).
