### ISSUE TITLE
Support smart punctuation

### ISSUE THREAD

**Issue by davidcelis** [voracious/ink-mde#54]
When GFM is involved, a common parsing/formatting option is to allow support for smart punctuation, so it would be nice to be able to configure Ink to use smart quotes/punctuation for writing and editing markdown, updating as punctuation, quotes, or matching quote-pairs are found. For example:

* `"Hello, world!" they exclaimed.` ➡️ “Hello, world!” they exclaimed.
* `That's a smart looking apostrophe.` ➡️ That’s a smart looking apostrophe.
* `The 's' is silent.` ➡️ The ‘s’ is silent.
* `2020--2022 was a bad time.` ➡️ 2020–2022 was a bad time.
* `I wondered---out loud---if they were being serious.` ➡️ I wondered—out loud—if they were being serious.
* `You don't say...` ➡️ You don’t say…
  * I think this one isn't usually included, but it's the other "smart punctuation" I miss that other editors or modern operating systems do for you 😅

**Comment by voracious** [comment]
This is an interesting idea. I could absolutely see this being implemented as a CodeMirror extension, but I'm not sure if it makes sense for Ink (although, I'd definitely welcome it in a PR). Let me think on this one a bit.

**Comment by davidcelis** [comment]
Understandable! I think this is one of those things that skirts the line between what some people feel is about writing experience and what others might feel is left up to the parser

**Comment by voracious** [comment]
After thinking about this some more, I think this could be done with some replacement decorations that make the quotes _look_ fancy while leaving the underlying text alone. Do you think that would be sufficient?

**Comment by davidcelis** [comment]
Hmmm, personally I think that might give the impression that the text itself was being modified, which could lead to some surprise when the content that's saved ends up being different than the content you're looking at…

Also, the more I think about this, the more I think that it's fine for this not to be Ink's responsibility; this feels like something that, if included anywhere, could be included in CodeMirror's markdown package, since smartypants/smart punctuation is pretty tied to Markdown as an option/extension. I opened this issue before I had dived as deeply into that world as I have now and I think at this point, the frustration that I'm facing is just that (at least in the Apple world) the smart punctuation that's baked into the OS is inconsistently applied and depends on whether or not an input is a true `input`, or a `contenteditable` element, or a CodeMirror editor, or a Monaco editor, etc, and that this behavior even differs between macOS and iOS. It's been a rabbit hole 😅

**Comment by voracious** [comment]
That all makes sense to me! The Plugin API for Ink will support raw CodeMirror extensions too, so including that CodeMirror extension would be a simple configuration change. If you end up going that route, I'd be happy to help you get that integrated too. Thanks for bearing with me on this and providing so much context. I'm going to close this issue for now, but I'm always happy to revisit this if it makes sense down the road.
