### ISSUE TITLE
Multi-line formatting does not work properly

### ISSUE THREAD

**Issue by preist** [voracious/ink-mde#58]
### Description

It seems that multi-line formatting does not work correctly (e.g. lists, quotes)

Preview:

![2023-02-20 20 12 03](https://user-images.githubusercontent.com/14940633/220176571-329b3852-2d53-47ce-ad6d-88614a46f4e3.gif)

Could be [this line](https://github.com/voracious/ink-mde/blob/309cac7d2fab923b2562e0e131f7ec12d1b90bde/src/api/format.ts#L199)?

**Comment by voracious** [comment]
This should be fixed in [`v0.22.0`](https://github.com/voracious/ink-mde/releases/tag/v0.22.0).
